name: a1
version: 1.0

dependencies:
  - base

library:
  exposed-modules:
    - ApplyAll
    - CartProd
    - Checksum
    - Magic
  source-dirs: src
  ghc-options: []
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

